cp_main:
	mkdir -p bin/ && g++ -fopenmp -g -O3 -march=native -std=c++17 -o bin/cp_main cp.cc cp_exp.cc

cp_256:
	mkdir -p bin/ && g++ -fopenmp -g -O3 -march=native -std=c++17 -o bin/cp_256 cp_256_vec.cc cp_exp.cc
