so_1:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_1 so_1.cc

so_2:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_2 so_2.cc

so_baseline:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_baseline so_baseline.cc
