so_1:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_1 so_1.cc

so_2:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_2 so_2.cc

so_baseline:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_baseline so_baseline.cc

so_parallel_sort:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_parallel_sort so_parallel_sort.cc

so_par_exp:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/so_par_exp so_par_exp.cc

bitonic:
	mkdir -p bin/ && g++ -fopenmp -g -O0 -march=native -std=c++17 -o bin/bitonic bitonic.cc
